import {
  AlarmClock,
  BellRing,
  CalendarCheck,
  CheckCircle2,
  Clock3,
  CreditCard,
  MessageCircle,
  PiggyBank,
  RotateCcw,
  Sparkles,
  Target,
} from 'lucide-react';

import type { WeeklyReview, WeeklyReviewListItem } from './weekly-review.types';

export const WEEKLY_REVIEW: WeeklyReview = {
  weekLabel: '2026년 6월 4주',
  summary: {
    title: '착수 12회 · 절약 86,000원',
    description: '이번 주 행동 변화를 숫자로 쌓았습니다.',
    savedAmount: '86,000원',
    startedCount: '12회',
  },
  summaryMetrics: [
    {
      id: 'routine',
      label: 'D7 유지',
      value: '5일 사용',
      description: '주간 루틴이 끊기지 않고 이어졌어요.',
      tone: 'success',
    },
    {
      id: 'goal',
      label: '후·선 착수',
      value: '달성',
      description: '계획한 착수 목표를 채웠습니다.',
      tone: 'caution',
    },
    {
      id: 'return-rate',
      label: '복귀율',
      value: '68%',
      description: '흔들린 뒤 다시 돌아온 비율입니다.',
      tone: 'premium',
    },
  ],
  plusFeatures: [
    {
      id: 'time',
      title: '시간대/감정/소비 패턴',
      description: '당신의 실행 패턴을 더 자세히 분석해요.',
      icon: CalendarCheck,
    },
    {
      id: 'context',
      title: '상황별 문장 추천',
      description: '자주 막히는 순간에 쓸 수 있는 문장을 제안해요.',
      icon: Sparkles,
    },
    {
      id: 'archive',
      title: '동기화/기록 보관',
      description: '기록을 오래 보관하고 흐름을 비교해요.',
      icon: BellRing,
    },
  ],
  insights: [
    {
      id: 'time-window',
      menu: '할일',
      badge: '할일 리포트',
      title: '시작이 쉬워진 시간대',
      description:
        '언제 착수가 잘 됐는지 패턴을 보여줍니다. 이번 주 당신의 황금 시간대를 확인해 보세요.',
      accent: 'blue',
      sections: [
        {
          id: 'best-time',
          subject: '착수 최다 시간',
          value: '오전 10시',
          description: '가장 자주 시작한 시간',
        },
        {
          id: 'average-start',
          subject: '평균 시작 지연',
          value: '-14분',
          description: '시작까지 걸린 시간 변화',
        },
        {
          id: 'recommend-time',
          subject: '추천',
          value: '오전 루틴 유지',
          description: '다음 주에도 유지하기 좋은 흐름',
        },
      ],
    },
    {
      id: 'spending-effect',
      menu: '소비',
      badge: '소비 리포트',
      title: '결제 3심이 효과를 냈어요',
      description: '보류와 취소 전환을 통해 실제 절약된 지출을 모았습니다.',
      accent: 'orange',
      sections: [
        {
          id: 'saved',
          subject: '절약 누적',
          value: '86,000원',
          description: '이번 주 아낀 금액',
        },
        {
          id: 'hold-rate',
          subject: '보류 성공률',
          value: '63%',
          description: '보류 후 결제를 멈춘 비율',
        },
      ],
    },
    {
      id: 'reset-return',
      menu: '감정',
      badge: '감정 리포트',
      title: '리셋 후 다시 돌아온 비율',
      description: '감정이 흔들렸던 순간과 행동 복귀율을 함께 봅니다.',
      accent: 'pink',
      sections: [
        {
          id: 'reset-count',
          subject: '리셋 사용',
          value: '6회',
          description: '흔들림을 알아차린 횟수',
        },
        {
          id: 'return-success',
          subject: '복귀 성공',
          value: '4회',
          description: '다시 루틴으로 돌아온 횟수',
        },
        {
          id: 'repeat-emotion',
          subject: '반복 감정',
          value: '불안',
          description: '가장 자주 기록된 감정',
        },
      ],
    },
    {
      id: 'dialogue',
      menu: '대화',
      badge: '대화 리포트',
      title: '자주 막힌 대화 상황',
      description: '복사·저장한 문장을 기반으로 필요한 말들을 추천합니다.',
      accent: 'purple',
      sections: [
        {
          id: 'request',
          subject: '최다 상황',
          value: '요청',
          description: '가장 자주 필요했던 대화',
        },
        {
          id: 'copy',
          subject: '복사',
          value: '5회',
          description: '도움이 된 문장 복사',
        },
        {
          id: 'saved-message',
          subject: '저장 문장',
          value: '2개',
          description: '다음에 다시 쓸 문장',
        },
      ],
    },
  ],
  goal: {
    title: '이번 주 목표를 달성했어요',
    description: '작은 성공을 다음 주 반복으로 연결합니다.',
    progressLabel: '4/4회 완료',
    completed: 4,
    total: 4,
  },
  recommendation: {
    title: '다음 주는 이렇게 해볼까요?',
    description: '이번 주 데이터를 바탕으로 더 나은 흐름을 위한 작은 조정을 제안합니다.',
    actions: [
      {
        id: 'alarm',
        label: '착수 알림',
        value: '오전 10시',
        description: '반복된 성공 시간에 맞춰 알려드려요.',
        tone: 'success',
      },
      {
        id: 'spending-goal',
        label: '소비 목표',
        value: '보류 10만원',
        description: '이번 주보다 조금 높은 절약 목표입니다.',
        tone: 'caution',
      },
      {
        id: 'recovery',
        label: '실패 단위',
        value: '10분 -> 7분',
        description: '복귀 시작 단위를 더 짧게 가져갑니다.',
        tone: 'premium',
      },
    ],
  },
};

export const WEEKLY_REVIEW_LIST_ITEMS = [
  {
    id: 'weekly-review-2026-06-4',
    year: 2026,
    month: 6,
    weekLabel: '2026년 6월 4주',
    title: '착수 12회 · 절약 86,000원',
    description: '오전 루틴과 결제 보류가 가장 선명했던 주간 리포트예요.',
    savedAmount: '86,000원',
    startedCount: '12회',
    returnRate: '68%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-06-3',
    year: 2026,
    month: 6,
    weekLabel: '2026년 6월 3주',
    title: '착수 9회 · 절약 42,000원',
    description: '루틴 재시작이 늘었고, 소비 보류 흐름이 처음 자리 잡았어요.',
    savedAmount: '42,000원',
    startedCount: '9회',
    returnRate: '61%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-06-2',
    year: 2026,
    month: 6,
    weekLabel: '2026년 6월 2주',
    title: '착수 7회 · 절약 28,000원',
    description: '작은 시작을 여러 번 남기며 다음 주 목표의 기준을 만들었어요.',
    savedAmount: '28,000원',
    startedCount: '7회',
    returnRate: '54%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-06-1',
    year: 2026,
    month: 6,
    weekLabel: '2026년 6월 1주',
    title: '착수 6회 · 절약 19,000원',
    description: '새 루틴을 작게 시작하며 소비 기록을 다시 남기기 시작했어요.',
    savedAmount: '19,000원',
    startedCount: '6회',
    returnRate: '48%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-05-4',
    year: 2026,
    month: 5,
    weekLabel: '2026년 5월 4주',
    title: '착수 10회 · 절약 64,000원',
    description: '할일 착수가 늘었고 결제 보류 성공률이 안정적으로 유지됐어요.',
    savedAmount: '64,000원',
    startedCount: '10회',
    returnRate: '66%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-05-3',
    year: 2026,
    month: 5,
    weekLabel: '2026년 5월 3주',
    title: '착수 8회 · 절약 37,000원',
    description: '감정 리셋 이후 다시 돌아온 기록이 가장 많이 쌓였어요.',
    savedAmount: '37,000원',
    startedCount: '8회',
    returnRate: '59%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-05-2',
    year: 2026,
    month: 5,
    weekLabel: '2026년 5월 2주',
    title: '착수 5회 · 절약 21,000원',
    description: '짧은 복귀 행동을 중심으로 루틴을 다시 연결했어요.',
    savedAmount: '21,000원',
    startedCount: '5회',
    returnRate: '52%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-05-1',
    year: 2026,
    month: 5,
    weekLabel: '2026년 5월 1주',
    title: '착수 4회 · 절약 16,000원',
    description: '기록 수는 적었지만 대화 문장을 저장하는 흐름이 생겼어요.',
    savedAmount: '16,000원',
    startedCount: '4회',
    returnRate: '45%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-04-4',
    year: 2026,
    month: 4,
    weekLabel: '2026년 4월 4주',
    title: '착수 11회 · 절약 73,000원',
    description: '오전 시작과 소비 보류가 함께 좋아졌던 주간 리포트예요.',
    savedAmount: '73,000원',
    startedCount: '11회',
    returnRate: '64%',
    href: '/review',
    plusHref: '/review/plus',
  },
  {
    id: 'weekly-review-2026-04-3',
    year: 2026,
    month: 4,
    weekLabel: '2026년 4월 3주',
    title: '착수 7회 · 절약 31,000원',
    description: '할일 착수는 줄었지만 감정 복귀는 꾸준히 이어졌어요.',
    savedAmount: '31,000원',
    startedCount: '7회',
    returnRate: '57%',
    href: '/review',
    plusHref: '/review/plus',
  },
] satisfies WeeklyReviewListItem[];

export const WEEKLY_REVIEW_SUMMARY_ICONS = [AlarmClock, Target, RotateCcw] as const;
export const WEEKLY_REVIEW_DETAIL_ICONS = [Clock3, CreditCard, RotateCcw, MessageCircle] as const;
export const WEEKLY_REVIEW_RECOMMENDATION_ICONS = [BellRing, PiggyBank, CheckCircle2] as const;
