import type {
  PaymentReviewHistoryItem,
  PaymentReviewOutcomeType,
  PaymentReviewStatus,
} from './payment-third-review.types';

export type PaymentReviewStatusDefinition = {
  description: string;
  label: string;
  outcomeType: PaymentReviewOutcomeType;
  status: PaymentReviewStatus;
};

export const PAYMENT_REVIEW_STATUS_DEFINITIONS: PaymentReviewStatusDefinition[] = [
  {
    description: '즉시 결제를 선택했고 24시간 뒤 만족도 체크가 예정된 상태입니다.',
    label: '결제 후 만족도 예정',
    outcomeType: 'buy',
    status: 'buy_satisfaction_scheduled',
  },
  {
    description: '즉시 결제 후 24시간이 지나 만족도 체크가 필요한 상태입니다.',
    label: '결제 후 만족도 필요',
    outcomeType: 'buy',
    status: 'buy_satisfaction_required',
  },
  {
    description: '즉시 결제 후 만족도 체크까지 완료된 상태입니다.',
    label: '결제 후 만족도 완료',
    outcomeType: 'buy',
    status: 'buy_satisfaction_completed',
  },
  {
    description: '처음부터 결제를 취소하고 목표 저축으로 반영한 상태입니다.',
    label: '저축 완료',
    outcomeType: 'save',
    status: 'save_completed',
  },
  {
    description: '24시간 보류를 선택했고 리마인드가 아직 도래하지 않은 상태입니다.',
    label: '보류 리마인드 예정',
    outcomeType: 'hold',
    status: 'hold_reminder_scheduled',
  },
  {
    description: '24시간 보류 후 리마인드 판단이 필요한 상태입니다.',
    label: '보류 리마인드 필요',
    outcomeType: 'hold',
    status: 'hold_reminder_required',
  },
  {
    description: '24시간 보류 후 결제 진행을 선택한 상태입니다.',
    label: '보류 후 결제',
    outcomeType: 'buy',
    status: 'hold_after_buy',
  },
  {
    description: '24시간 보류 후 결제 미진행을 선택해 저축으로 볼 수 있는 상태입니다.',
    label: '보류 후 저축',
    outcomeType: 'save',
    status: 'hold_after_save',
  },
  {
    description: '24시간 보류 후 다시 보류를 선택해 3일 뒤 재보류 리마인드가 예정된 상태입니다.',
    label: '재보류 예정',
    outcomeType: 'hold',
    status: 'hold_after_hold_scheduled',
  },
  {
    description: '재보류를 선택했고 3일 뒤 리마인드가 아직 도래하지 않은 상태입니다.',
    label: '재보류 리마인드 예정',
    outcomeType: 'hold',
    status: 'rehold_reminder_scheduled',
  },
  {
    description: '재보류 후 3일이 지나 다시 판단이 필요한 상태입니다.',
    label: '재보류 리마인드 필요',
    outcomeType: 'hold',
    status: 'rehold_reminder_required',
  },
  {
    description: '재보류 이후 결제 진행을 선택한 상태입니다.',
    label: '재보류 후 결제',
    outcomeType: 'buy',
    status: 'rehold_after_buy',
  },
  {
    description: '재보류 이후 결제 미진행을 선택해 저축으로 볼 수 있는 상태입니다.',
    label: '재보류 후 저축',
    outcomeType: 'save',
    status: 'rehold_after_save',
  },
  {
    description: '재보류 이후 다시 보류를 선택해 추가 리마인드가 예정된 상태입니다.',
    label: '추가 보류 예정',
    outcomeType: 'hold',
    status: 'rehold_after_hold_scheduled',
  },
];

export const PAYMENT_REVIEW_HISTORY_ITEMS: PaymentReviewHistoryItem[] = [
  {
    id: 'ptr-001',
    itemName: '무선 이어폰',
    date: '오늘',
    amount: '62,000원',
    impulseStrength: '높음',
    decision: '그래도 결제',
    decisionType: 'buy',
    outcomeType: 'buy',
    reason: '업무 효율에 필요',
    followUpLabel: '24시간 뒤',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 72%',
    budgetImpactLabel: '이번 달 소비에 기록',
    status: 'buy_satisfaction_scheduled',
    satisfaction: {
      status: 'scheduled',
    },
  },
  {
    id: 'ptr-006',
    itemName: '노트북 파우치',
    date: '어제',
    amount: '32,000원',
    impulseStrength: '보통',
    decision: '그래도 결제',
    decisionType: 'buy',
    outcomeType: 'buy',
    reason: '기존 파우치가 낡아서 교체',
    followUpLabel: '지금 진행',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 80%',
    budgetImpactLabel: '이번 달 소비에 기록',
    status: 'buy_satisfaction_required',
    satisfaction: {
      status: 'required',
    },
  },
  {
    id: 'ptr-007',
    itemName: '무선 충전기',
    date: '6월 20일',
    amount: '28,900원',
    impulseStrength: '낮음',
    decision: '그래도 결제',
    decisionType: 'buy',
    outcomeType: 'buy',
    reason: '책상 충전 동선을 줄이기 위해 구매',
    followUpLabel: '만족도 4/5',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 69%',
    budgetImpactLabel: '이번 달 소비에 기록',
    status: 'buy_satisfaction_completed',
    satisfaction: {
      status: 'completed',
      result: {
        checkedAt: '6월 21일',
        memo: '매일 사용하고 있고 충전 위치가 정리돼서 만족도가 높아요.',
        score: 4,
        summary: '만족',
      },
    },
  },
  {
    id: 'ptr-003',
    itemName: '카페 디저트',
    date: '6월 18일',
    amount: '24,600원',
    impulseStrength: '낮음',
    decision: '취소하고 목표에 저축',
    decisionType: 'save',
    outcomeType: 'save',
    reason: '목표 저축에 반영',
    followUpLabel: '목표 저축',
    followUpType: 'saved',
    progressLabel: '목표 대비 64%',
    budgetImpactLabel: '24,600원 절약',
    status: 'save_completed',
  },
  {
    id: 'ptr-005',
    itemName: '디자인 구독',
    date: '6월 12일',
    amount: '19,900원',
    impulseStrength: '높음',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '대체 서비스 확인 필요',
    followUpLabel: '24시간 뒤',
    followUpType: 'reminder',
    progressLabel: '목표 대비 88%',
    budgetImpactLabel: '결제 보류 중',
    status: 'hold_reminder_scheduled',
    reminder: {
      reminderCount: 1,
      status: 'scheduled',
    },
  },
  {
    id: 'ptr-002',
    itemName: '무선 키보드',
    date: '6월 21일',
    amount: '78,400원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '하루 뒤에도 필요한지 재확인',
    followUpLabel: '지금 진행',
    followUpType: 'reminder',
    progressLabel: '목표 대비 91%',
    budgetImpactLabel: '결제 보류 중',
    status: 'hold_reminder_required',
    reminder: {
      reminderCount: 1,
      status: 'required',
    },
  },
  {
    id: 'ptr-010',
    itemName: '블루투스 마우스',
    date: '6월 19일',
    amount: '41,000원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'buy',
    reason: '하루 뒤에도 업무에 필요하다고 판단',
    followUpLabel: '보류 후 결제',
    followUpType: 'reminder',
    progressLabel: '목표 대비 83%',
    budgetImpactLabel: '이번 달 소비에 기록',
    status: 'hold_after_buy',
    reminder: {
      reminderCount: 1,
      status: 'completed',
      result: {
        completedType: 'after-first-hold',
        decision: 'buy',
        memo: '하루 뒤에도 필요해서 결제를 진행했어요.',
        submittedAt: '6월 20일',
      },
    },
  },
  {
    id: 'ptr-008',
    itemName: '태블릿 거치대',
    date: '6월 17일',
    amount: '34,900원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'save',
    reason: '하루 뒤에도 업무 책상에 필요한지 확인',
    followUpLabel: '보류 후 저축',
    followUpType: 'reminder',
    progressLabel: '목표 대비 70%',
    budgetImpactLabel: '34,900원 소비 방지',
    status: 'hold_after_save',
    reminder: {
      reminderCount: 1,
      status: 'completed',
      result: {
        completedType: 'after-first-hold',
        decision: 'cancel',
        memo: '하루 지나고 보니 급하지 않아서 구매하지 않았어요.',
        submittedAt: '6월 18일',
      },
    },
  },
  {
    id: 'ptr-011',
    itemName: '키보드 손목 받침대',
    date: '6월 16일',
    amount: '22,000원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '조금 더 사용 패턴을 보고 결정',
    followUpLabel: '3일 뒤',
    followUpType: 'reminder',
    progressLabel: '목표 대비 74%',
    budgetImpactLabel: '재보류 중',
    status: 'hold_after_hold_scheduled',
    reminder: {
      reminderCount: 2,
      status: 'scheduled',
    },
  },
  {
    id: 'ptr-012',
    itemName: '데스크 조명',
    date: '6월 15일',
    amount: '48,000원',
    impulseStrength: '낮음',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '재보류 이후에도 사용 빈도를 확인 중',
    followUpLabel: '3일 뒤',
    followUpType: 'reminder',
    progressLabel: '목표 대비 78%',
    budgetImpactLabel: '재보류 리마인드 예정',
    status: 'rehold_reminder_scheduled',
    reminder: {
      reminderCount: 2,
      status: 'scheduled',
    },
  },
  {
    id: 'ptr-013',
    itemName: '외장 SSD',
    date: '6월 14일',
    amount: '96,000원',
    impulseStrength: '높음',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '재보류 후 다시 판단 필요',
    followUpLabel: '지금 진행',
    followUpType: 'reminder',
    progressLabel: '목표 대비 99%',
    budgetImpactLabel: '재보류 판단 필요',
    status: 'rehold_reminder_required',
    reminder: {
      reminderCount: 2,
      status: 'required',
    },
  },
  {
    id: 'ptr-014',
    itemName: '책상 정리함',
    date: '6월 13일',
    amount: '18,500원',
    impulseStrength: '낮음',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'buy',
    reason: '재보류 후에도 실제 필요가 유지됨',
    followUpLabel: '재보류 후 결제',
    followUpType: 'reminder',
    progressLabel: '목표 대비 67%',
    budgetImpactLabel: '이번 달 소비에 기록',
    status: 'rehold_after_buy',
    reminder: {
      reminderCount: 2,
      status: 'completed',
      result: {
        completedType: 'after-rehold',
        decision: 'buy',
        memo: '3일 더 고민한 뒤에도 필요해서 결제를 진행했어요.',
        submittedAt: '6월 16일',
      },
    },
  },
  {
    id: 'ptr-009',
    itemName: '운동화',
    date: '6월 14일',
    amount: '89,000원',
    impulseStrength: '높음',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'save',
    reason: '가격 비교와 실제 필요성을 더 확인',
    followUpLabel: '재보류 후 저축',
    followUpType: 'reminder',
    progressLabel: '목표 대비 96%',
    budgetImpactLabel: '재보류 후 결제 미진행',
    status: 'rehold_after_save',
    reminder: {
      reminderCount: 2,
      status: 'completed',
      result: {
        completedType: 'after-rehold',
        decision: 'cancel',
        memo: '3일 더 지나도 필요성이 낮아서 구매하지 않았어요.',
        submittedAt: '6월 18일',
      },
    },
  },
  {
    id: 'ptr-015',
    itemName: '스마트 플러그',
    date: '6월 11일',
    amount: '27,000원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    outcomeType: 'hold',
    reason: '재보류 이후에도 설치 위치가 확정되지 않음',
    followUpLabel: '추가 보류',
    followUpType: 'reminder',
    progressLabel: '목표 대비 82%',
    budgetImpactLabel: '추가 보류 중',
    status: 'rehold_after_hold_scheduled',
    reminder: {
      reminderCount: 3,
      status: 'scheduled',
    },
  },
];

// 결제 3심 기록 id에 맞는 히스토리 항목을 반환합니다.
export function getPaymentReviewHistoryItemById(id: string) {
  return PAYMENT_REVIEW_HISTORY_ITEMS.find((item) => item.id === id);
}
