import type { PaymentReviewHistoryItem } from './payment-third-review.types';

export const PAYMENT_REVIEW_HISTORY_ITEMS: PaymentReviewHistoryItem[] = [
  {
    id: 'ptr-001',
    itemName: '무선 이어폰',
    date: '오늘',
    amount: '62,000원',
    impulseStrength: '높음',
    decision: '그래도 결제',
    decisionType: 'buy',
    reason: '업무 효율에 필요',
    followUpLabel: '24시간 뒤',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 72%',
    budgetImpactLabel: '이번 달 소비에 기록',
    satisfaction: {
      status: 'scheduled',
    },
  },
  {
    id: 'ptr-002',
    itemName: '무선 키보드',
    date: '6월 21일',
    amount: '78,400원',
    impulseStrength: '보통',
    decision: '24시간 보류',
    decisionType: 'hold',
    reason: '하루 뒤에도 필요한지 재확인',
    followUpLabel: '내일 오후 8시',
    followUpType: 'reminder',
    progressLabel: '목표 대비 91%',
    budgetImpactLabel: '결제 보류 중',
  },
  {
    id: 'ptr-006',
    itemName: '노트북 파우치',
    date: '어제',
    amount: '32,000원',
    impulseStrength: '보통',
    decision: '그래도 결제',
    decisionType: 'buy',
    reason: '기존 파우치가 낡아서 교체',
    followUpLabel: '지금 진행',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 80%',
    budgetImpactLabel: '이번 달 소비에 기록',
    satisfaction: {
      status: 'required',
    },
  },
  {
    id: 'ptr-007',
    itemName: '무선 충전기',
    date: '6월 20일',
    amount: '28,900원',
    impulseStrength: '낮음',
    decision: '그래도 결제',
    decisionType: 'buy',
    reason: '책상 충전 동선을 줄이기 위해 구매',
    followUpLabel: '만족도 4/5',
    followUpType: 'satisfaction',
    progressLabel: '목표 대비 69%',
    budgetImpactLabel: '이번 달 소비에 기록',
    satisfaction: {
      status: 'completed',
      result: {
        checkedAt: '6월 21일',
        memo: '매일 사용하고 있고 충전 위치가 정리돼서 만족도가 높아요.',
        score: 4,
        summary: '만족',
      },
    },
  },
  {
    id: 'ptr-003',
    itemName: '카페 디저트',
    date: '6월 18일',
    amount: '24,600원',
    impulseStrength: '낮음',
    decision: '취소하고 목표에 저축',
    decisionType: 'save',
    reason: '목표 저축에 반영',
    followUpLabel: '목표 저축',
    followUpType: 'saved',
    progressLabel: '목표 대비 64%',
    budgetImpactLabel: '24,600원 절약',
  },
  {
    id: 'ptr-004',
    itemName: '장보기 추가 품목',
    date: '6월 15일',
    amount: '53,200원',
    impulseStrength: '보통',
    decision: '취소하고 목표에 저축',
    decisionType: 'save',
    reason: '자기보상으로 저장',
    followUpLabel: '주간 보상 후보',
    followUpType: 'saved',
    progressLabel: '목표 대비 76%',
    budgetImpactLabel: '53,200원 절약',
  },
  {
    id: 'ptr-005',
    itemName: '디자인 구독',
    date: '6월 12일',
    amount: '19,900원',
    impulseStrength: '높음',
    decision: '24시간 보류',
    decisionType: 'hold',
    reason: '대체 서비스 확인 필요',
    followUpLabel: '24시간 뒤',
    followUpType: 'reminder',
    progressLabel: '목표 대비 88%',
    budgetImpactLabel: '결제 보류 중',
  },
];

// 결제 3심 기록 id에 맞는 히스토리 항목을 반환합니다.
export function getPaymentReviewHistoryItemById(id: string) {
  return PAYMENT_REVIEW_HISTORY_ITEMS.find((item) => item.id === id);
}
